from enum import StrEnum


class EdiMessageDirection(StrEnum):
    INBOUND = "INBOUND"
    OUTBOUND = "OUTBOUND"


class EdiMessageStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    FAILED = "FAILED"
    DUPLICATE = "DUPLICATE"
    CANCELLED = "CANCELLED"


class EdiMessageEventType(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    PROCESSING_STARTED = "PROCESSING_STARTED"
    RELATED_ENTITY_CREATED = "RELATED_ENTITY_CREATED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    OUTBOUND_REQUESTED = "OUTBOUND_REQUESTED"
    OUTBOUND_ACCEPTED = "OUTBOUND_ACCEPTED"


class EdiRelatedEntityType(StrEnum):
    CUSTOMER_PO = "CUSTOMER_PO"
    SALES_ORDER = "SALES_ORDER"
    PURCHASE_ORDER = "PURCHASE_ORDER"
    SHIPMENT = "SHIPMENT"
    INVOICE = "INVOICE"
